build-job:
  stage: build
  image: gitlab/gitlab-runner:ubuntu
  script: |
    apt install -y python3.11-venv
    python3 -m venv ../.atst ; ../.atst/bin/python3 -m pip install --upgrade .
    ../.atst/bin/endorlabs-atst setup
  