build-job:
  stage: build
  image: ubuntu:22.04
  script: |
    apt install -y python3-venv
    python3 -m venv ../.atst ; ../.atst/bin/python3 -m pip install --upgrade .
    ../.atst/bin/endorlabs-atst setup
  