name: Endor Labs AT-ST Self-Scan
on: push

jobs:
  endorlabs-setup-and-scan:
    permissions:
      contents: read    # Required by actions/checkout@v3 to checkout a private repository.
    runs-on: ubuntu-latest
    env:
      DEBUG: 1
      ENDOR_API_CREDENTIALS_KEY: ${{ vars.ENDORLABS_API_KEY }}
      ENDOR_API_CREDENTIALS_SECRET: ${{ secrets.ENDORLABS_API_SECRET }}
      ENDOR_NAMESPACE: darren-learn
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
      - name: Endor Labs Setup
        run: |
          python3 -m venv ../.atst ; ../.atst/bin/python3 -m pip -q install --upgrade .
          ../.atst/bin/endorlabs-atst setup

      - name: Endor Labs Host Check
        run: endorlabs-atst ctl -- scan --ci-run
